title: My personal site
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is Douwe personal home page

# social links
twitter_username: douwevincent # DO NOT include the @ character, or else the build will fail!
github_username:  douwevincent # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
